### ISSUE TITLE
Manve central missed 0.28 version

### ISSUE THREAD

**Issue by sleshJdev** [InsanusMokrassar/TelegramBotAPI#127]
Hi
![image](https://user-images.githubusercontent.com/3650340/92323255-e4c5de00-f03f-11ea-9a90-8f19fc30d675.png)
Seems that 0.28 already published but it's not available in maven central. Is it accidentally or there is some policy about that? 
Thanks

**Comment by InsanusMokrassar** [comment]
Hello, usually it is enough to publish library in jcenter, for this reason I am rarely publish artifacts to maven. Currently I am publishing it to the maven central and it must be available in that near time

**Comment by sleshJdev** [comment]
> Hello, usually it is enough to publish library in jcenter, for this reason I am rarely publish artifacts to maven. Currently I am publishing it to the maven central and it must be available in that near time

Does it mean that maven central will be decommissioned soon? Jcenter is superset of maven central so I'd expect that artifacts will be published in maven central first.

**Comment by InsanusMokrassar** [comment]
1. No, but I do not plan to publish artifacts to maven at the same time as in jcenter, but if you think it would be appropriate to do this for each version - I will try hard to do publication for maven on each new version
2. As I know, JCenter is not a superset for maven. I think, it is more like a replacement for maveb in some cases due to the more simple publication procedure

**Comment by sleshJdev** [comment]
>     1. if you think it would be appropriate to do this for each version - I will try hard to do publication for maven on each new version

It's not needed. Feel free to it in the way which you think is better. I just raised a few questions which concerned me. Thanks for your reply
