### ISSUE TITLE
WaitContent functions get updates not from the current chat

### ISSUE THREAD

**Issue by ithersta** [InsanusMokrassar/TelegramBotAPI#621]
Is it an expected behavior that `wait*()` functions get all updates even not from the current chat? If so, is it possible to filter them based on chat id?

**Comment by InsanusMokrassar** [comment]
Hello, it is expected behaviour. You may use any operations available for flows, you may use [waitContentMessage](https://tgbotapi.inmo.dev/docs/dev.inmo.tgbotapi.extensions.behaviour_builder.expectations/wait-content-message.html) with data [filtering](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/filter.html). For example:

```kotlin
waitContentMessage().filter {
    it.chat.id == someChatId
}.first().content
```

**Comment by InsanusMokrassar** [comment]
You are always welcome in our [telegram chat](https://t.me/InMoTelegramBotAPIChat)
